"""Make emails unique

Revision ID: 941d3daf60e1
Revises: 0f2b30049435
Create Date: 2018-06-05 00:45:33.099455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941d3daf60e1'
down_revision = '0f2b30049435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
